---
name: internal-pr-style

on:
  pull_request:
    types:
      - synchronize
      - edited

defaults:
  run:
    shell: bash

permissions:
  pull-requests: write

jobs:

  pr-style:
    uses: ./.github/workflows/pr-style.yml
