---
name: internal-release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  tag-and-release:
    uses: ./.github/workflows/tag-and-release.yml
    with:
      change-filters: |
        workflows:
          - '.github/workflows/**'
    secrets: inherit
