---
name: internal-pr

on:
  pull_request:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      any-workflow-changed: ${{ steps.detect-changes.outputs.any_workflow == 'true' }}
      external-workflow-changed: ${{ steps.detect-changes.outputs.external_workflows == 'true' }}
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: dorny/paths-filter@v3
        id: detect-changes
        with:
          filters: |
            any_workflow:
              - '.github/actions/**'
              - '.github/workflows/**'
            external_workflows:
              - '.github/actions/**'
              - '.github/workflows/pr-style.yml'
              - '.github/workflows/tag-and-release.yml'

  lint:
    needs: [setup]
    if: ${{ needs.setup.outputs.any-workflow-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Install yamllint
        run: sudo apt-get install yamllint
      -
        name: Lint
        run: make lint

  preview-release:
    needs: [setup]
    if: ${{ needs.setup.outputs.external-workflow-changed == 'true' }}
    uses: ./.github/workflows/tag-and-release.yml
    with:
      dry-run: true
      tag-prefix: v
      change-filters: |
        workflows:
          - '.github/actions/**'
          - '.github/workflows/pr-style.yml'
          - '.github/workflows/tag-and-release.yml'

  pr-ready:
    runs-on: ubuntu-latest
    needs:
      - setup
      - lint
      - preview-release
    if: ${{ always() }}
    steps:
      -
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')  }}
        run: |
          echo "One or more jobs did not succeed: ${{ toJson(needs.*.result) }}"
          exit 1
