name: internal-pr-style

on:
  pull_request:
    types:
      - synchronize
      - edited

defaults:
  run:
    shell: bash

jobs:

  pr-style:
    uses: ./.github/workflows/pr-style.yml
    with:
      REQUIRE_BODY: true
      CREATE_COMMENT: true