---
name: internal-release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  tag-and-release:
    uses: ./.github/workflows/tag-and-release.yml
    with:
      tag-prefix: v
      change-filters: |
        workflows:
          - '.github/workflows/pr-style.yml'
          - '.github/workflows/tag-and-release.yml'
    secrets: inherit
