---
name: internal-pr

on:
  pull_request:
    types:
      - synchronize

defaults:
  run:
    shell: bash

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install yamllint
        run: sudo apt-get install yamllint

      - name: Lint
        run: make lint
