---
name: tag-and-release

on:
  workflow_call:
    inputs:
      tag-prefix:
        type: string
        required: false
        description: Tag prefix
        default: v
      change-filters:
        type: string
        required: false
        description: Optional path filters for change detection
    secrets:
      GH_TOKEN:
        description: Optional token to use for Github operations
        required: false
    outputs:
      version:
        value: ${{ jobs.tag-and-release.outputs.version }}
      version-tag:
        value: ${{ jobs.tag-and-release.outputs.version-tag }}
      released:
        value: ${{ jobs.tag-and-release.outputs.create-release }}

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:

  tag-and-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag-and-release.outputs.version }}
      version-tag: ${{ steps.tag-and-release.outputs.version_tag }}
      create-release: ${{ steps.tag-and-release.outputs.should-tag }}
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN || github.token }}
      -
        uses: ./.github/actions/tag-and-release
        id: tag-and-release
        with:
          tag-prefix: ${{ inputs.tag-prefix }}
          change-filters: ${{ inputs.change-filters }}
